import TNumbersLean.DiophantineBudget
import TNumbersLean.FourierBudget
import TNumbersLean.DigitBudget
import TNumbersLean.HeightOverlap
import TNumbersLean.ScheduleBudget
import TNumbersLean.KoksmaExponent
import TNumbersLean.CriterionInputs
import TNumbersLean.HeightRangeCoverage
