import TNumbersLean

#print axioms TNumbersLean.cubic_gap
#print axioms TNumbersLean.usable_numerator_half
#print axioms TNumbersLean.usable_exponent_lower
#print axioms TNumbersLean.K_add_one
#print axioms TNumbersLean.overlap_exponent_identity
#print axioms TNumbersLean.overlap_budget
#print axioms TNumbersLean.B_exponent_identity
#print axioms TNumbersLean.normalized_lower_identity
#print axioms TNumbersLean.normalized_lower_ge

#print axioms TNumbersLean.derivative_scale_identity
#print axioms TNumbersLean.perturbation_exponent_identity
#print axioms TNumbersLean.derivative_budget

#print axioms TNumbersLean.block_constant_512
#print axioms TNumbersLean.block_constant_8192
#print axioms TNumbersLean.digit_exponent_budget
#print axioms TNumbersLean.digit_power_exponent
#print axioms TNumbersLean.two_pow_fifty
#print axioms TNumbersLean.next_scale_exponent_identity

#print axioms TNumbersLean.height_in_current_range


#print axioms TNumbersLean.consecutive_admissible_gap_le_two
#print axioms TNumbersLean.skipped_stage_not_admissible
#print axioms TNumbersLean.skipped_degree_le
#print axioms TNumbersLean.stageExponent_le_of_degree_le
#print axioms TNumbersLean.skipped_stage_exponent_le
#print axioms TNumbersLean.two_step_schedule_exponent_le
#print axioms TNumbersLean.one_step_schedule_exponent_le

#print axioms TNumbersLean.AlgebraicApproximationSystem.admissible_le_wStar
#print axioms TNumbersLean.AlgebraicApproximationSystem.upper_bound_bridge
#print axioms TNumbersLean.AlgebraicApproximationSystem.lower_bound_bridge
#print axioms TNumbersLean.AlgebraicApproximationSystem.t_number_bridge
#print axioms TNumbersLean.CriterionInputs.source_approximation_Q
#print axioms TNumbersLean.CriterionInputs.admissible_exponent_lower
#print axioms TNumbersLean.CriterionInputs.usable_exponent_lower
#print axioms TNumbersLean.AlgebraicApproximationSystem.isTNumber_iff_tail_unbounded

#print axioms TNumbersLean.CriterionSchedule.scheduleCoeff_cast
#print axioms TNumbersLean.CriterionSchedule.height_delta_eq
#print axioms TNumbersLean.CriterionSchedule.height_delta_pos
#print axioms TNumbersLean.CriterionSchedule.scale_pos
#print axioms TNumbersLean.CriterionSchedule.scale_ge_one
#print axioms TNumbersLean.CriterionSchedule.scale_strictMono
#print axioms TNumbersLean.CriterionSchedule.heightLeft_strictMono
#print axioms TNumbersLean.CriterionSchedule.usableExponent_pos
#print axioms TNumbersLean.CriterionSchedule.scale_two_step
#print axioms TNumbersLean.CriterionSchedule.consecutive_stage_cases
#print axioms TNumbersLean.CriterionSchedule.consecutive_scale_gap_nat
#print axioms TNumbersLean.CriterionSchedule.scale_gap_power_eq
#print axioms TNumbersLean.CriterionSchedule.exists_eventual_scale_gap
#print axioms TNumbersLean.CriterionSchedule.height_overlap_of_scale_gap
#print axioms TNumbersLean.CriterionSchedule.exists_eventual_height_overlap
#print axioms TNumbersLean.CriterionSchedule.admissible_infinite
#print axioms TNumbersLean.CriterionSchedule.exists_admissible_ge
#print axioms TNumbersLean.CriterionSchedule.heightLeft_tends_to_infinity
#print axioms TNumbersLean.CriterionSchedule.eventually_heightLeft_gt
#print axioms TNumbersLean.CriterionSchedule.exists_admissible_heightLeft_gt
#print axioms TNumbersLean.CriterionSchedule.exists_last_admissible_pair
#print axioms TNumbersLean.CriterionSchedule.exists_height_cover

#print axioms TNumbersLean.propositionB_eq
#print axioms TNumbersLean.CriterionInputs.local_separation
#print axioms TNumbersLean.CriterionInputs.source_error_factorization
#print axioms TNumbersLean.CriterionInputs.source_error_ratio_bound
#print axioms TNumbersLean.CriterionInputs.absorbed_local_bound
#print axioms TNumbersLean.CriterionInputs.usableExponent_uniform_lower
#print axioms TNumbersLean.CriterionInputs.eventually_admissible_heightRight_ge
#print axioms TNumbersLean.CriterionInputs.transcendence
#print axioms TNumbersLean.CriterionInputs.covered_scale_factor
#print axioms TNumbersLean.CriterionInputs.height_half_absorption
#print axioms TNumbersLean.CriterionInputs.global_separation_uniform
#print axioms TNumbersLean.CriterionInputs.global_separation
#print axioms TNumbersLean.CriterionInputs.upper_wStar_bound
#print axioms TNumbersLean.CriterionInputs.wStar_lt_top
#print axioms TNumbersLean.CriterionInputs.denominator_tends_to_infinity
#print axioms TNumbersLean.CriterionInputs.center_height_tends_to_infinity
#print axioms TNumbersLean.CriterionInputs.recurrent_center_heights_unbounded
#print axioms TNumbersLean.CriterionInputs.recurrent_centers_infinite
#print axioms TNumbersLean.CriterionInputs.recurrent_source_bound
#print axioms TNumbersLean.CriterionInputs.eventually_recurrent_strong_approximation
#print axioms TNumbersLean.CriterionInputs.recurrent_exact_approximants_infinite
#print axioms TNumbersLean.CriterionInputs.recurrent_approximants_infinite
#print axioms TNumbersLean.CriterionInputs.lower_wStar_bound
#print axioms TNumbersLean.CriterionInputs.normalized_lower_bound
#print axioms TNumbersLean.CriterionInputs.normalized_ge_degree
#print axioms TNumbersLean.CriterionInputs.normalized_tail_unbounded
#print axioms TNumbersLean.CriterionInputs.normalized_tends_to_top
#print axioms TNumbersLean.CriterionInputs.isTNumber
#print axioms TNumbersLean.proposition_three_two

#print axioms TNumbersLean.ScheduleThresholds.availableDegrees
#print axioms TNumbersLean.ScheduleThresholds.selectDegree
#print axioms TNumbersLean.ScheduleThresholds.v₂
#print axioms TNumbersLean.ScheduleThresholds.pairScale
#print axioms TNumbersLean.ScheduleThresholds.concreteD
#print axioms TNumbersLean.ScheduleThresholds.concreteDegree
#print axioms TNumbersLean.ScheduleThresholds.concreteExponent
#print axioms TNumbersLean.ScheduleThresholds.concreteQ

#print axioms TNumbersLean.ScheduleThresholds.availableDegrees_nonempty
#print axioms TNumbersLean.ScheduleThresholds.selectDegree_spec
#print axioms TNumbersLean.ScheduleThresholds.selectDegree_maximal
#print axioms TNumbersLean.ScheduleThresholds.selectDegree_mem
#print axioms TNumbersLean.ScheduleThresholds.selectDegree_greatest
#print axioms TNumbersLean.ScheduleThresholds.stageExponent_pos
#print axioms TNumbersLean.ScheduleThresholds.scale_update_ge
#print axioms TNumbersLean.ScheduleThresholds.pairScale_initial_le
#print axioms TNumbersLean.ScheduleThresholds.concreteD_spec
#print axioms TNumbersLean.ScheduleThresholds.concreteD_maximal
#print axioms TNumbersLean.ScheduleThresholds.concrete_availableDegrees_nonempty
#print axioms TNumbersLean.ScheduleThresholds.concreteD_isGreatest
#print axioms TNumbersLean.ScheduleThresholds.concreteDegree_even
#print axioms TNumbersLean.ScheduleThresholds.concreteDegree_odd
#print axioms TNumbersLean.ScheduleThresholds.concreteQ_even
#print axioms TNumbersLean.ScheduleThresholds.concreteQ_odd
#print axioms TNumbersLean.ScheduleThresholds.concreteDegree_ge_two
#print axioms TNumbersLean.ScheduleThresholds.concreteDegree_le_pair
#print axioms TNumbersLean.ScheduleThresholds.concreteExponent_bounds
#print axioms TNumbersLean.ScheduleThresholds.concreteQ_recurrence
#print axioms TNumbersLean.ScheduleThresholds.concreteQ_initial_le
#print axioms TNumbersLean.ScheduleThresholds.concreteQ_ge_four
#print axioms TNumbersLean.ScheduleThresholds.concreteQ_strictMono
#print axioms TNumbersLean.ScheduleThresholds.concreteQ_growth
#print axioms TNumbersLean.ScheduleThresholds.concreteQ_tends_to_infinity
#print axioms TNumbersLean.ScheduleThresholds.concreteQ_real_tends_to_infinity
#print axioms TNumbersLean.ScheduleThresholds.pairScale_tends_to_infinity
#print axioms TNumbersLean.ScheduleThresholds.eventually_concreteD_ge
#print axioms TNumbersLean.ScheduleThresholds.concreteD_tends_to_infinity
#print axioms TNumbersLean.ScheduleThresholds.concrete_threshold
#print axioms TNumbersLean.ScheduleThresholds.v₂_nonneg
#print axioms TNumbersLean.ScheduleThresholds.recurrentDegree_ge_two
#print axioms TNumbersLean.ScheduleThresholds.v₂_witness
#print axioms TNumbersLean.ScheduleThresholds.v₂_fiber_infinite
#print axioms TNumbersLean.ScheduleThresholds.concrete_recurrent
#print axioms TNumbersLean.ScheduleThresholds.eventual_odd_admissible
#print axioms TNumbersLean.ScheduleThresholds.concrete_eventual_next_admissible
#print axioms TNumbersLean.ScheduleThresholds.concrete_eventual_scale_gap
#print axioms TNumbersLean.ScheduleThresholds.lemma_three_one
#print axioms TNumbersLean.ScheduleThresholds.concreteCriterionSchedule

-- Actual rational algebraicity, primitive integer minimal polynomial height, and Northcott.
#print axioms TNumbersLean.RealAlgebraicData.isAlg
#print axioms TNumbersLean.RealAlgebraicData.degree
#print axioms TNumbersLean.RealAlgebraicData.clearedMinpoly
#print axioms TNumbersLean.RealAlgebraicData.primitiveMinpoly
#print axioms TNumbersLean.RealAlgebraicData.coefficientHeight
#print axioms TNumbersLean.RealAlgebraicData.naiveHeight
#print axioms TNumbersLean.RealAlgebraicData.IsPrimitiveMinimalPolynomial
#print axioms TNumbersLean.RealAlgebraicData.degree_pos
#print axioms TNumbersLean.RealAlgebraicData.degree_eq_finrank
#print axioms TNumbersLean.RealAlgebraicData.isAlg_add_rat
#print axioms TNumbersLean.RealAlgebraicData.degree_add_rat
#print axioms TNumbersLean.RealAlgebraicData.clearedMinpoly_ne_zero
#print axioms TNumbersLean.RealAlgebraicData.primitiveMinpoly_isPrimitive
#print axioms TNumbersLean.RealAlgebraicData.primitiveMinpoly_ne_zero
#print axioms TNumbersLean.RealAlgebraicData.primitiveMinpoly_map
#print axioms TNumbersLean.RealAlgebraicData.primitiveMinpoly_aeval
#print axioms TNumbersLean.RealAlgebraicData.primitiveMinpoly_irreducible_map
#print axioms TNumbersLean.RealAlgebraicData.primitiveMinpoly_irreducible
#print axioms TNumbersLean.RealAlgebraicData.primitiveMinpoly_identification
#print axioms TNumbersLean.RealAlgebraicData.primitiveMinpoly_natDegree
#print axioms TNumbersLean.RealAlgebraicData.abs_coeff_le_coefficientHeight
#print axioms TNumbersLean.RealAlgebraicData.coefficientHeight_attained
#print axioms TNumbersLean.RealAlgebraicData.coefficientHeight_eq_max
#print axioms TNumbersLean.RealAlgebraicData.coefficientHeight_neg
#print axioms TNumbersLean.RealAlgebraicData.coefficientHeight_ge_one
#print axioms TNumbersLean.RealAlgebraicData.naiveHeight_ge_one
#print axioms TNumbersLean.RealAlgebraicData.associated_eq_or_neg
#print axioms TNumbersLean.RealAlgebraicData.primitiveMinpoly_unique_sign
#print axioms TNumbersLean.RealAlgebraicData.naiveHeight_eq_of_primitive_minimal
#print axioms TNumbersLean.RealAlgebraicData.degree_eq_of_primitive_minimal
#print axioms TNumbersLean.RealAlgebraicData.bounded_integer_coefficients_finite
#print axioms TNumbersLean.RealAlgebraicData.bounded_polynomials_finite
#print axioms TNumbersLean.RealAlgebraicData.northcott
#print axioms TNumbersLean.realAlgebraicApproximationSystem
#print axioms TNumbersLean.realAlgebraicApproximationSystem_isAlg
#print axioms TNumbersLean.realAlgebraicApproximationSystem_degree
#print axioms TNumbersLean.realAlgebraicApproximationSystem_height

-- Concrete E witnesses and Section 2 inputs; no literal proposition wrapper.
#print axioms TNumbersLean.theta
#print axioms TNumbersLean.theta_pos
#print axioms TNumbersLean.theta_pow
#print axioms TNumbersLean.theta_le_two
#print axioms TNumbersLean.theta_polynomial_irreducible
#print axioms TNumbersLean.theta_minpoly
#print axioms TNumbersLean.theta_algebraic
#print axioms TNumbersLean.theta_degree
#print axioms TNumbersLean.theta_translate_degree
#print axioms TNumbersLean.StageWitness
#print axioms TNumbersLean.MemE
#print axioms TNumbersLean.memE_stage_witness
#print axioms TNumbersLean.MemE.numerator
#print axioms TNumbersLean.MemE.denominator
#print axioms TNumbersLean.MemE.witness_spec
#print axioms TNumbersLean.MemE.denominator_pos
#print axioms TNumbersLean.MemE.reduced
#print axioms TNumbersLean.MemE.denominator_block
#print axioms TNumbersLean.MemE.rational
#print axioms TNumbersLean.MemE.center
#print axioms TNumbersLean.MemE.rational_cast
#print axioms TNumbersLean.MemE.source_approximation
#print axioms TNumbersLean.MemE.center_algebraic
#print axioms TNumbersLean.MemE.center_exact_degree
#print axioms TNumbersLean.MemE.source_error_le_one
#print axioms TNumbersLean.MemE.center_mem_bounds
#print axioms TNumbersLean.MemE.rational_bound
#print axioms TNumbersLean.concreteCriterionInputs

#print axioms TNumbersLean.SectionTwoInputs

-- Final concrete Proposition 3.2 and paper-facing corollaries.
#print axioms TNumbersLean.concrete_proposition_three_two
#print axioms TNumbersLean.concrete_transcendence
#print axioms TNumbersLean.concrete_global_separation
#print axioms TNumbersLean.concrete_upper_wStar
#print axioms TNumbersLean.concrete_lower_wStar
#print axioms TNumbersLean.concrete_isTNumber

-- Theorem 1.1: perfect-set extraction.
#print axioms TNumbersLean.exists_compact_perfect_subset_of_pos_measure

-- Theorem 1.1: Weyl-normality infrastructure.
#print axioms TNumbersLean.circleExp
#print axioms TNumbersLean.weylTerm
#print axioms TNumbersLean.weylSum
#print axioms TNumbersLean.normalizedWeylSum
#print axioms TNumbersLean.norm_circleExp
#print axioms TNumbersLean.norm_weylTerm
#print axioms TNumbersLean.norm_weylSum_le
#print axioms TNumbersLean.norm_weylSum_sub_le
#print axioms TNumbersLean.WeylNormalToBase
#print axioms TNumbersLean.WeylAbsolutelyNormal
#print axioms TNumbersLean.square_gap_le
#print axioms TNumbersLean.squareBadSet
#print axioms TNumbersLean.ae_eventually_square_control
#print axioms TNumbersLean.norm_weylSum_between_squares
#print axioms TNumbersLean.nat_sqrt_square_bounds
#print axioms TNumbersLean.norm_weylSum_sqrt_interpolation
#print axioms TNumbersLean.tendsto_zero_of_eventually_le_inv_nat
#print axioms TNumbersLean.squareNormRatio
#print axioms TNumbersLean.squareNormRatio_nonneg
#print axioms TNumbersLean.squareNormRatio_eventually_le
#print axioms TNumbersLean.squareNormRatio_tendsto_zero_of_reciprocal_control
#print axioms TNumbersLean.ae_squareNormRatio_tendsto_zero_of_summable_bad
#print axioms TNumbersLean.natSqrt_tendsto_atTop
#print axioms TNumbersLean.squareGapRatio
#print axioms TNumbersLean.squareGapRatio_tendsto_zero
#print axioms TNumbersLean.squareGapRatio_sqrt_tendsto_zero
#print axioms TNumbersLean.paperFourier
#print axioms TNumbersLean.paperFourier_apply
#print axioms TNumbersLean.conj_circleExp
#print axioms TNumbersLean.circleExp_add
#print axioms TNumbersLean.weylFrequency
#print axioms TNumbersLean.conj_weylTerm_mul_weylTerm
#print axioms TNumbersLean.integrable_weylCorrelation
#print axioms TNumbersLean.integral_weylCorrelation
#print axioms TNumbersLean.ofReal_normSq_weylSum_eq_doubleSum
#print axioms TNumbersLean.integral_normSq_weylSum_eq_doubleFourier
#print axioms TNumbersLean.weylFrequency_diag
#print axioms TNumbersLean.paperFourier_zero
#print axioms TNumbersLean.two_pow_le_pow_sub_pow
#print axioms TNumbersLean.abs_weylFrequency_lower_bound
#print axioms TNumbersLean.weylSecondMoment
#print axioms TNumbersLean.weylSecondMoment_eq_re_doubleFourier
#print axioms TNumbersLean.weylSecondMoment_le_doubleNormSum
#print axioms TNumbersLean.paperDecayProfile
#print axioms TNumbersLean.HasPaperFourierDecay
#print axioms TNumbersLean.paperDecayProfile_le_of_abs_ge
#print axioms TNumbersLean.paperFourier_offdiag_decay
#print axioms TNumbersLean.stretchedExpMomentTerm
#print axioms TNumbersLean.summable_stretchedExpMomentTerm
#print axioms TNumbersLean.double_sum_le_diag_add_two_triangle

-- Theorem 1.1: completed Fourier/Borel--Cantelli chain.
#print axioms TNumbersLean.lacunaryFourierMomentTerm
#print axioms TNumbersLean.lacunaryFourierMomentTerm_nonneg
#print axioms TNumbersLean.lacunaryFourierMomentTerm_le_stretched
#print axioms TNumbersLean.summable_lacunaryFourierMomentTerm
#print axioms TNumbersLean.sum_lacunaryFourierMomentTerm_le_tsum
#print axioms TNumbersLean.fourierOffDiagonalConstant
#print axioms TNumbersLean.fourierOffDiagonalConstant_nonneg
#print axioms TNumbersLean.weylSecondMoment_le_linear

#print axioms TNumbersLean.integrable_normSq_weylSum
#print axioms TNumbersLean.measureReal_squareBadSet_weyl_le_inv_sq
#print axioms TNumbersLean.summable_measureReal_squareBadSet_weyl
#print axioms TNumbersLean.tsum_measure_ne_top_of_summable_measureReal
#print axioms TNumbersLean.tsum_squareBadSet_weyl_ne_top
#print axioms TNumbersLean.ae_squareNormRatio_weyl_tendsto_zero

#print axioms TNumbersLean.norm_normalizedWeylSum_eq_div
#print axioms TNumbersLean.norm_normalizedWeylSum_le_square_terms
#print axioms TNumbersLean.normalizedWeylSum_tendsto_zero_of_squareNormRatio
#print axioms TNumbersLean.ae_normalizedWeylSum_tendsto_zero_of_fourierDecay
#print axioms TNumbersLean.ae_weylNormalToBase_of_fourierDecay
#print axioms TNumbersLean.ae_weylAbsolutelyNormal_of_fourierDecay

#print axioms TNumbersLean.exists_compact_perfect_weylAbsolutelyNormal_subset_of_pos_measure
#print axioms TNumbersLean.exists_compact_perfect_weylAbsolutelyNormal_TNumbers
#print axioms TNumbersLean.exists_compact_perfect_weylAbsolutelyNormal_TNumbers_of_compact

#print axioms TNumbersLean.PacketStageWitness
#print axioms TNumbersLean.PacketStageWitness.toStageWitness
#print axioms TNumbersLean.memE_of_packetStageWitness
#print axioms TNumbersLean.tendsto_paperDecayProfile_atTop
#print axioms TNumbersLean.tendsto_norm_paperFourier_atTop_of_decay

#print axioms TNumbersLean.tendsto_norm_charFun_atTop_of_paperDecay
#print axioms TNumbersLean.measureMassIncrementBudget
#print axioms TNumbersLean.hasSum_measureMassIncrementBudget
#print axioms TNumbersLean.abs_mass_sub_one_le_one_sixteenth
#print axioms TNumbersLean.mass_mem_Icc_fifteen_sixteen_seventeen_sixteen
#print axioms TNumbersLean.primePacketSupport
#print axioms TNumbersLean.mem_primePacketSupport_iff_packetStageWitness
#print axioms TNumbersLean.memE_of_mem_manuscriptPacketSet
#print axioms TNumbersLean.exists_compact_perfect_weylAbsolutelyNormal_TNumbers_of_packetSupport

-- Packet Fourier arithmetic.
#print axioms TNumbersLean.fullPacketResidueSum
#print axioms TNumbersLean.fullPacketResidueSum_eq
#print axioms TNumbersLean.packetResidueSum
#print axioms TNumbersLean.packetResidueSum_eq
#print axioms TNumbersLean.packetResidueFactor
#print axioms TNumbersLean.packetResidueFactor_eq
#print axioms TNumbersLean.packetResidueFactor_eq_manuscript

-- Fourier translation and scaling for packet bumps.
#print axioms TNumbersLean.packetFourier
#print axioms TNumbersLean.packetFourier_def
#print axioms TNumbersLean.packetFourier_translate
#print axioms TNumbersLean.packetFourier_scale
#print axioms TNumbersLean.packetFourier_scale_pos
#print axioms TNumbersLean.packetFourier_affine_pos

-- Exact Fourier transform of an individual packet bump.
#print axioms TNumbersLean.paperBumpComplex
#print axioms TNumbersLean.complexPacketBumpTerm
#print axioms TNumbersLean.packetFourier_complexPacketBumpTerm
#print axioms TNumbersLean.packetFourier_scaled_complexPacketBumpTerm

-- Schwartz periodization bridge.
#print axioms TNumbersLean.schwartzContinuousMap
#print axioms TNumbersLean.schwartz_periodization_local_summable
#print axioms TNumbersLean.fourierCoeff_periodization_schwartz

-- Packet bumps as Schwartz functions.
#print axioms TNumbersLean.paperBumpComplex_hasCompactSupport
#print axioms TNumbersLean.paperBumpComplex_contDiff
#print axioms TNumbersLean.paperBumpSchwartz
#print axioms TNumbersLean.affinePacketBumpComplex
#print axioms TNumbersLean.affinePacketBumpComplex_eq
#print axioms TNumbersLean.affinePacketBumpComplex_contDiff
#print axioms TNumbersLean.affinePacketBumpComplex_hasCompactSupport
#print axioms TNumbersLean.affinePacketBumpSchwartz

-- Fourier coefficients of periodized packet bumps.
#print axioms TNumbersLean.periodizedAffinePacketBump
#print axioms TNumbersLean.fourierCoeff_periodizedAffinePacketBump
#print axioms TNumbersLean.fourierCoeff_periodizedAffinePacketBump_eq

#print axioms TNumbersLean.fourierChar_rational_phase_eq_stdAddChar

-- Exact Fourier coefficient of a single prime packet.
#print axioms TNumbersLean.packetPhaseSum
#print axioms TNumbersLean.packetStdAddCharSum_eq_packetResidueSum
#print axioms TNumbersLean.packetPhaseSum_eq_packetResidueSum
#print axioms TNumbersLean.fourierChar_affine_zmod_phase_factor
#print axioms TNumbersLean.fourierChar_affine_zmod_phase_factor_intVal
#print axioms TNumbersLean.periodizedPrimePacketCoeff
#print axioms TNumbersLean.periodizedPrimePacketCoeff_eq_residueFactor
#print axioms TNumbersLean.periodizedPrimePacketCoeff_eq_manuscript

-- Prime divisors in a packet window.
#print axioms TNumbersLean.packetPrimeDivisors
#print axioms TNumbersLean.mem_packetPrimeDivisors_iff
#print axioms TNumbersLean.packetPrimeDivisors_subset_primeFactors
#print axioms TNumbersLean.prod_packetPrimeDivisors_dvd
#print axioms TNumbersLean.pow_card_packetPrimeDivisors_le
#print axioms TNumbersLean.card_packetPrimeDivisors_le_natLog

-- Real-logarithmic packet divisor count.
#print axioms TNumbersLean.card_packetPrimeDivisors_le_log_div
#print axioms TNumbersLean.card_packetPrimeDivisors_le_padded_log_div
#print axioms TNumbersLean.card_packetPrimeDivisors_natAbs_le_padded_log_div

-- Dyadic prime-count input interface.
#print axioms TNumbersLean.PrimePacketCountInputs
#print axioms TNumbersLean.PrimePacketCountInputs.packetPrimes_nonempty
#print axioms TNumbersLean.PrimePacketCountInputs.packetPrimes_card_ne_zero

-- Quadratic Fourier decay of the normalized paper bump.
#print axioms TNumbersLean.paperBumpFourierSchwartz
#print axioms TNumbersLean.paperBumpFourierSchwartz_apply
#print axioms TNumbersLean.paperBumpFourierDecayConstant
#print axioms TNumbersLean.paperBumpFourierDecayConstant_nonneg
#print axioms TNumbersLean.paperBumpFourier_weighted_decay
#print axioms TNumbersLean.norm_packetFourier_paperBump_le

-- Formula-side Fourier coefficient of the averaged packet.
#print axioms TNumbersLean.primePacketCoeffFormula
#print axioms TNumbersLean.primePacketCoeffFormula_eq_periodized
#print axioms TNumbersLean.averagedPacketCoeffFormula
#print axioms TNumbersLean.norm_averagedPacketCoeffFormula_le
#print axioms TNumbersLean.norm_primePacketCoeffFormula

-- Residue-factor bounds in the averaged packet.
#print axioms TNumbersLean.packetResidueFormula
#print axioms TNumbersLean.packetResidueFormula_eq_factor
#print axioms TNumbersLean.norm_packetResidueFormula_of_dvd
#print axioms TNumbersLean.norm_packetResidueFormula_of_not_dvd
#print axioms TNumbersLean.norm_packetResidueFormula_le_window
#print axioms TNumbersLean.norm_packetResidueFormula_le_indicator_add
#print axioms TNumbersLean.sum_norm_packetResidueFormula_le

-- Uniform bump Fourier decay across a dyadic packet.
#print axioms TNumbersLean.norm_packetFourier_paperBump_scaled_le

-- Combined averaged-packet coefficient envelope.
#print axioms TNumbersLean.norm_primePacketCoeffFormula_eq_bump_mul_residue
#print axioms TNumbersLean.norm_primePacketCoeffFormula_le_uniform
#print axioms TNumbersLean.norm_averagedPacketCoeffFormula_le_envelope

-- Normalized prime-divisor ratio in a packet.
#print axioms TNumbersLean.packetPrimeDivisor_ratio_le
#print axioms TNumbersLean.norm_inv_packetPrimes_card
