import TNumbersLean

#print axioms TNumbersLean.cubic_gap
#print axioms TNumbersLean.usable_numerator_half
#print axioms TNumbersLean.usable_exponent_lower
#print axioms TNumbersLean.K_add_one
#print axioms TNumbersLean.overlap_exponent_identity
#print axioms TNumbersLean.overlap_budget
#print axioms TNumbersLean.B_exponent_identity
#print axioms TNumbersLean.normalized_lower_identity
#print axioms TNumbersLean.normalized_lower_ge

#print axioms TNumbersLean.derivative_scale_identity
#print axioms TNumbersLean.perturbation_exponent_identity
#print axioms TNumbersLean.derivative_budget

#print axioms TNumbersLean.block_constant_512
#print axioms TNumbersLean.block_constant_8192
#print axioms TNumbersLean.digit_exponent_budget
#print axioms TNumbersLean.digit_power_exponent
#print axioms TNumbersLean.two_pow_fifty
#print axioms TNumbersLean.next_scale_exponent_identity

#print axioms TNumbersLean.height_in_current_range


#print axioms TNumbersLean.consecutive_admissible_gap_le_two
#print axioms TNumbersLean.skipped_stage_not_admissible
#print axioms TNumbersLean.skipped_degree_le
#print axioms TNumbersLean.stageExponent_le_of_degree_le
#print axioms TNumbersLean.skipped_stage_exponent_le
#print axioms TNumbersLean.two_step_schedule_exponent_le
#print axioms TNumbersLean.one_step_schedule_exponent_le

#print axioms TNumbersLean.AlgebraicApproximationSystem.admissible_le_wStar
#print axioms TNumbersLean.AlgebraicApproximationSystem.upper_bound_bridge
#print axioms TNumbersLean.AlgebraicApproximationSystem.lower_bound_bridge
#print axioms TNumbersLean.AlgebraicApproximationSystem.t_number_bridge
#print axioms TNumbersLean.CriterionInputs.source_approximation_Q
#print axioms TNumbersLean.CriterionInputs.admissible_exponent_lower
#print axioms TNumbersLean.CriterionInputs.usable_exponent_lower
#print axioms TNumbersLean.AlgebraicApproximationSystem.isTNumber_iff_tail_unbounded
