import TNumbersLean

#print axioms TNumbersLean.cubic_gap
#print axioms TNumbersLean.usable_numerator_half
#print axioms TNumbersLean.usable_exponent_lower
#print axioms TNumbersLean.K_add_one
#print axioms TNumbersLean.overlap_exponent_identity
#print axioms TNumbersLean.overlap_budget
#print axioms TNumbersLean.B_exponent_identity
#print axioms TNumbersLean.normalized_lower_identity
#print axioms TNumbersLean.normalized_lower_ge

#print axioms TNumbersLean.derivative_scale_identity
#print axioms TNumbersLean.perturbation_exponent_identity
#print axioms TNumbersLean.derivative_budget

#print axioms TNumbersLean.block_constant_512
#print axioms TNumbersLean.block_constant_8192
#print axioms TNumbersLean.digit_exponent_budget
#print axioms TNumbersLean.digit_power_exponent
#print axioms TNumbersLean.two_pow_fifty
#print axioms TNumbersLean.next_scale_exponent_identity

#print axioms TNumbersLean.height_in_current_range


#print axioms TNumbersLean.consecutive_admissible_gap_le_two
#print axioms TNumbersLean.skipped_stage_not_admissible
#print axioms TNumbersLean.skipped_degree_le
#print axioms TNumbersLean.stageExponent_le_of_degree_le
#print axioms TNumbersLean.skipped_stage_exponent_le
#print axioms TNumbersLean.two_step_schedule_exponent_le
#print axioms TNumbersLean.one_step_schedule_exponent_le

#print axioms TNumbersLean.AlgebraicApproximationSystem.admissible_le_wStar
#print axioms TNumbersLean.AlgebraicApproximationSystem.upper_bound_bridge
#print axioms TNumbersLean.AlgebraicApproximationSystem.lower_bound_bridge
#print axioms TNumbersLean.AlgebraicApproximationSystem.t_number_bridge
#print axioms TNumbersLean.CriterionInputs.source_approximation_Q
#print axioms TNumbersLean.CriterionInputs.admissible_exponent_lower
#print axioms TNumbersLean.CriterionInputs.usable_exponent_lower
#print axioms TNumbersLean.AlgebraicApproximationSystem.isTNumber_iff_tail_unbounded

#print axioms TNumbersLean.CriterionSchedule.scheduleCoeff_cast
#print axioms TNumbersLean.CriterionSchedule.height_delta_eq
#print axioms TNumbersLean.CriterionSchedule.height_delta_pos
#print axioms TNumbersLean.CriterionSchedule.scale_pos
#print axioms TNumbersLean.CriterionSchedule.scale_ge_one
#print axioms TNumbersLean.CriterionSchedule.scale_strictMono
#print axioms TNumbersLean.CriterionSchedule.heightLeft_strictMono
#print axioms TNumbersLean.CriterionSchedule.usableExponent_pos
#print axioms TNumbersLean.CriterionSchedule.scale_two_step
#print axioms TNumbersLean.CriterionSchedule.consecutive_stage_cases
#print axioms TNumbersLean.CriterionSchedule.consecutive_scale_gap_nat
#print axioms TNumbersLean.CriterionSchedule.scale_gap_power_eq
#print axioms TNumbersLean.CriterionSchedule.exists_eventual_scale_gap
#print axioms TNumbersLean.CriterionSchedule.height_overlap_of_scale_gap
#print axioms TNumbersLean.CriterionSchedule.exists_eventual_height_overlap
#print axioms TNumbersLean.CriterionSchedule.admissible_infinite
#print axioms TNumbersLean.CriterionSchedule.exists_admissible_ge
#print axioms TNumbersLean.CriterionSchedule.heightLeft_tends_to_infinity
#print axioms TNumbersLean.CriterionSchedule.eventually_heightLeft_gt
#print axioms TNumbersLean.CriterionSchedule.exists_admissible_heightLeft_gt
#print axioms TNumbersLean.CriterionSchedule.exists_last_admissible_pair
#print axioms TNumbersLean.CriterionSchedule.exists_height_cover

#print axioms TNumbersLean.propositionB_eq
#print axioms TNumbersLean.CriterionInputs.local_separation
#print axioms TNumbersLean.CriterionInputs.source_error_factorization
#print axioms TNumbersLean.CriterionInputs.source_error_ratio_bound
#print axioms TNumbersLean.CriterionInputs.absorbed_local_bound
#print axioms TNumbersLean.CriterionInputs.usableExponent_uniform_lower
#print axioms TNumbersLean.CriterionInputs.eventually_admissible_heightRight_ge
#print axioms TNumbersLean.CriterionInputs.transcendence
#print axioms TNumbersLean.CriterionInputs.covered_scale_factor
#print axioms TNumbersLean.CriterionInputs.height_half_absorption
#print axioms TNumbersLean.CriterionInputs.global_separation_uniform
#print axioms TNumbersLean.CriterionInputs.global_separation
#print axioms TNumbersLean.CriterionInputs.upper_wStar_bound
#print axioms TNumbersLean.CriterionInputs.wStar_lt_top
#print axioms TNumbersLean.CriterionInputs.denominator_tends_to_infinity
#print axioms TNumbersLean.CriterionInputs.center_height_tends_to_infinity
#print axioms TNumbersLean.CriterionInputs.recurrent_center_heights_unbounded
#print axioms TNumbersLean.CriterionInputs.recurrent_centers_infinite
#print axioms TNumbersLean.CriterionInputs.recurrent_source_bound
#print axioms TNumbersLean.CriterionInputs.eventually_recurrent_strong_approximation
#print axioms TNumbersLean.CriterionInputs.recurrent_exact_approximants_infinite
#print axioms TNumbersLean.CriterionInputs.recurrent_approximants_infinite
#print axioms TNumbersLean.CriterionInputs.lower_wStar_bound
#print axioms TNumbersLean.CriterionInputs.normalized_lower_bound
#print axioms TNumbersLean.CriterionInputs.normalized_ge_degree
#print axioms TNumbersLean.CriterionInputs.normalized_tail_unbounded
#print axioms TNumbersLean.CriterionInputs.normalized_tends_to_top
#print axioms TNumbersLean.CriterionInputs.isTNumber
#print axioms TNumbersLean.proposition_three_two
